### ISSUE TITLE
Can't get startDate and endDate in UsosTimeTableActivity

### ISSUE THREAD

**Issue by matkedzierski** [WMS-DEV/usos4j#15]
Hi Team!
In the beginning, I'm really grateful for developing such a great and useful adapter for our "lovely" USOS.

Recently I've started using usos4j for my project that integrates with external calendar sources. I was interested in using the timetables API of USOS. I got a little confused, since UsosTimeTableActivity has startTime and endTime fields, but they're not accessible - they have a default/package-private access level. I guess that those fields, together with type, name and URL should have getters, or lombok's Value annotation as used in UsosTimeTableClassGroupActivity?

Could you please look into it? If that's a problem, I can try to make my own PR, but just wanted to know if you plan to work on that soon!

Many thanks!
Mateusz

**Comment by pszumanski** [comment]
Hi @matkedzierski!

Thank you very much for reporting this issue, which got fixed in latest 1.1.4 version. Our team is glad that you decided to use usos4j in your project and we would love to see it when you are finished!

Should you find any further issues, do not hesitate to contact us.

Good luck with your project!
Piotr
